export const DISPATCH_ACTION = {
  SEARCH_PROJECT_BY_FIELD: 'SEARCH_PROJECT_BY_FIELD',
  MOCKING_PROJECTS_ITEM: 'MOCKING_PROJECTS_ITEM',
  ADD_PROJECT_ITEM: 'ADD_PROJECT_ITEM',
  UPDATE_PROJECT_ITEM: 'UPDATE_PROJECT_ITEM',
  DELETE_PROJECT_ITEM: 'DELETE_PROJECT_ITEM',
  SET_SELECTED_PROJECT: 'SET_SELECTED_PROJECT',
  CLEAR_SELECTED_PROJECT: 'CLEAR_SELECTED_PROJECT'
} as const;
